"use client";

import { updatePost } from "@/actions/actions";
import { useActionState } from "react";

// 1. Define props type so the component receives the post data
type Post = {
  id: number; 
  title: string;
  content: string;
};

export default function UpdatePostForm({ post }: { post: Post }) {
  // 2. Bind the post.id as the first argument to updatePost
  const updatePostWithId = updatePost.bind(null, post.id);

  // 3. Pass the bound function to useActionState
  const [state, formAction] = useActionState(updatePostWithId, null);

  return (
    // 4. Use formAction generated by useActionState
    <form action={formAction} className="space-y-5">
      {/* Display error message if validation fails */}
      {state?.error && (
        <div className="p-3 text-sm text-red-700 bg-red-100 rounded-md">
          {state.error}
        </div>
      )}

      <div>
        <label
          htmlFor="title"
          className="mb-2 block text-sm font-medium text-gray-700"
        >
          Title
        </label>
        <input
          id="title"
          name="title"
          type="text"
          defaultValue={post.title}
          className="w-full text-black rounded-lg border border-gray-300 px-4 py-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
        />
      </div>

      <div>
        <label
          htmlFor="content"
          className="mb-2 block text-sm font-medium text-gray-700"
        >
          Content
        </label>
        <textarea
          id="content"
          name="content"
          rows={7}
          defaultValue={post.content}
          className="w-full text-black resize-none rounded-lg border border-gray-300 px-4 py-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"
        />
      </div>

      <button
        type="submit"
        className="rounded-lg bg-blue-600 px-6 py-3 font-medium text-white transition hover:bg-blue-700"
      >
        Update Note
      </button>
    </form>
  );
}